[workspace]
resolver = "2"
members = [
    "core",
    "gui",
    "db",
    "macros",
]
default-members = ["gui"]

# We specify dependencies we use in multiple places here, so we can make sure
# every crate uses the same version.
[workspace.dependencies]
macros = { path = "macros" }
db = { path = "db" }
core = { path = "core" }
gui = { path = "gui" }

chrono = "0.4.42"
tokio = { version = "1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
thiserror = "2.0.17"
convert_case = "0.10.0"

mavinspect = { version = "0.6.6" }
mavspec = { version = "0.6.7", features = ["definitions", "metadata", "std"] }
maviola = { version = "0.3.0", features = ["async", "dlct-standard", "dlct-common", "dlct-ardupilotmega"] }
rapid-dialect = { git = "https://github.com/tudsat-rocket/rapid-dialect", features = ["definitions"] }

egui = { version = "0.32" }
egui-wgpu = { version = "0.32" }
egui-winit = { version = "0.32" }
eframe = { version = "0.32" }
egui_plot = "0.33"
egui_extras = { version = "0.32", features = ["image"] }

[workspace.lints.clippy]
# Groups
pedantic = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

# opt-outs for pedantic group
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
float_cmp = "allow"
format_collect = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
must_use_candidate = "allow"
return_self_not_must_use = "allow"
too_many_lines = "allow"
unused_self = "allow"
single_match_else = "allow"

# opt-ins for restrictions group, we should aspire to enable more of these
#allow_attributes_without_reason = "warn"
#arithmetic_side_effects = "warn"
#as_conversions = "warn"
assertions_on_result_states = "warn"
#clone_on_ref_ptr = "warn"
#else_if_without_else = "warn"
#expect_used = "warn"
#indexing_slicing = "warn"
#integer_division_remainder_used = "warn"
#let_underscore_must_use = "warn"
map_err_ignore = "warn"
mem_forget = "warn"
panic = "warn"
redundant_type_annotations = "warn"
same_name_method = "warn"
#shadow_reuse = "warn"
#shadow_same = "warn"
#shadow_unrelated = "warn"
todo = "warn"
unimplemented = "warn"
#unreachable = "warn"
unused_result_ok = "warn"
unused_trait_names = "warn"
unwrap_in_result = "warn"
#unwrap_used = "warn"

# opt-outs for cargo group
multiple_crate_versions = "allow" # TODO
cargo_common_metadata = "allow" # TODO
