[package]
name = "gui"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { workspace = true }

chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

mavspec = { workspace = true }
maviola = { workspace = true }

egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }
eframe = { workspace = true }
egui_plot = { workspace = true }
egui_extras = { workspace = true }
egui_tiles = "0.13"
egui_tracing = { git = "https://github.com/KoffeinFlummi/egui_tracing", branch = "egui0.32" }
walkers = "0.44"
