[package]
name = "gui"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { workspace = true }

chrono = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

mavspec = { workspace = true }
maviola = { workspace = true }

egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { workspace = true }
eframe = { workspace = true }
egui_plot = { workspace = true }
egui_extras = { workspace = true }
egui_tiles = "0.13"
egui-notify = "0.20"
egui_tracing = { git = "https://github.com/KoffeinFlummi/egui_tracing", branch = "egui0.32" }
walkers = "0.46"

# profiling feature
puffin = { git = "https://github.com/EmbarkStudios/puffin", optional = true }
puffin_egui = { git = "https://github.com/EmbarkStudios/puffin", optional = true }
nalgebra = "0.34.1"

[features]
default = []
profiling = ["dep:puffin", "dep:puffin_egui"]

[lints]
workspace = true
