[package]
name = "core"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
db = { workspace = true }

chrono = { workspace = true }
directories = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

mavspec = { workspace = true }
maviola = { workspace = true }
rapid-dialect = { workspace = true }
socketcan = { version = "3.5.0", features = [ "tokio" ] }
tokio-serial = "5.4.5"

[lints]
workspace = true
