[package]
name = "db"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros = { workspace = true }

chrono = { workspace = true }
thiserror = { workspace = true }

mavspec = { workspace = true, features = ["rust-dialects", "dlct-ardupilotmega"] }
mavinspect = { version = "0.6.6" }
rapid-dialect = { workspace = true }

[lints]
workspace = true
