[package]
name = "macros"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
tracing = { workspace = true }

mavspec = { workspace = true }
mavinspect = { version = "0.6.6" }

[lints]
workspace = true
